name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Install ESLint dependencies
      run: npm install --save-dev eslint @eslint/js typescript-eslint eslint-plugin-react

    - name: Lint code
      run: npx eslint .

    # Docker build
    - name: Build Docker image
      run: docker build -t gestion-etablissement-backend:${{ github.sha }} .

    # Sauvegarder l'image pour le déploiement
    - name: Save Docker image
      run: docker save gestion-etablissement-backend:${{ github.sha }} > gestion-etablissement-backend.tar

    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: gestion-etablissement-backend.tar

  deploy-dev:
    needs: build-and-lint
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3

    - name: Download Docker image
      uses: actions/download-artifact@v4
      with:
        name: docker-image

    - name: Load Docker image
      run: docker load < gestion-etablissement-backend.tar

    - name: Deploy to Dev environment
      run: |
        echo "Déploiement sur l'environnement de développement"
        # Ici, vous ajouteriez les commandes pour déployer sur votre environnement de développement

  deploy-staging:
    needs: deploy-dev
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubectl
      run: |
        echo "Configuration de kubectl pour accéder au cluster Kubernetes"

    - name: Deploy to Staging environment
      run: |
        echo "Déploiement sur l'environnement de staging (K8s)"

  deploy-prod:
    needs: deploy-staging
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3

    - name: Deploy to Production environment
      run: |
        echo "Déploiement sur l'environnement de production"
